// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck

/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.27.0.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

export interface InstantiateMsg {
  terraswap_factory: string;
}
export type ExecuteMsg =
  | {
      receive: Cw20ReceiveMsg;
    }
  | {
      execute_swap_operations: {
        minimum_receive?: Uint128 | null;
        operations: SwapOperation[];
        to?: string | null;
      };
    }
  | {
      execute_swap_operation: {
        operation: SwapOperation;
        to?: string | null;
      };
    }
  | {
      assert_minimum_receive: {
        asset_info: AssetInfo;
        minimum_receive: Uint128;
        prev_balance: Uint128;
        receiver: string;
      };
    }
  | {
      add_swap_routes: {
        swap_routes: SwapRoute[];
      };
    };
export type Uint128 = string;
export type Binary = string;
export type SwapOperation = {
  terra_swap: {
    ask_asset_info: AssetInfo;
    offer_asset_info: AssetInfo;
  };
};
export type NativeToken = {
  denom: string;
};

export type Token = {
  contract_addr: string;
};
export type AssetInfo = Token | NativeToken;
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
}
export interface SwapRoute {
  ask_asset_info: AssetInfo;
  offer_asset_info: AssetInfo;
  swap_operations: SwapOperation[];
}
export type QueryMsg =
  | {
      config: {};
    }
  | {
      simulate_swap_operations: {
        offer_amount: Uint128;
        operations: SwapOperation[];
      };
    }
  | {
      reverse_simulate_swap_operations: {
        ask_amount: Uint128;
        operations: SwapOperation[];
      };
    }
  | {
      swap_route: {
        ask_asset_info: AssetInfo;
        offer_asset_info: AssetInfo;
      };
    };
export interface MigrateMsg {}
export interface ConfigResponse {
  terraswap_factory: string;
}
export interface SimulateSwapOperationsResponse {
  amount: Uint128;
}
export type ArrayOfSwapOperation = SwapOperation[];
